---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubectl-audit-permissions
rules:
  - apiGroups:
      - certificates.k8s.io
    resources:
      - signers
    resourceNames:
      - kubernetes.io/kubelet-serving
    verbs:
      - approve
  - apiGroups:
      - "certificates.k8s.io"
    resources:
      - certificatesigningrequests
      - certificatesigningrequests/approval
    verbs:
      - get
      - create
      - delete
      - update
  - apiGroups:
      - spreadgroup.com
    resources:
      - accessrequests
      - accessgrants
    verbs:
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubectl-audit-permissions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubectl-audit-permissions
subjects:
  - kind: ServiceAccount
    name: kubectl-audit
    namespace: default
