resources:
  - kubectl-audit.yaml
  - kubectl-audit-rbac.yaml
  - validating-admission-webhook.yaml
  # crds
  - request-crd.yaml
  - grant-crd.yaml
  # example deployment to play around with
  - nginx-deployment.yaml
  # example role for "developers" locally
  - developer-role.yaml
configMapGenerator:
  - name: kubectl-audit-certs
    files:
      - localhost.key
      - localhost.crt
