apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: accessrequests.spreadgroup.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: spreadgroup.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - userInfo
                - execOptions
              properties:
                userInfo:
                  type: object
                  required:
                    - username
                  properties:
                    username:
                      type: string
                execOptions:
                  type: object
                  x-kubernetes-embedded-resource: true
                  x-kubernetes-preserve-unknown-fields: true
                  properties:
                    kind:
                      type: string
                      pattern: PodExecOptions
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: accessrequests
    # singular name to be used as an alias on the CLI and for display
    singular: accessrequest
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: AccessRequest
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - acr
