apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kube-request-access-webhook
webhooks:
- name: kube-request-access.default.svc
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    resources:   ["pods/exec"]
    operations: ["*"]
    scope:       "Namespaced"
  - apiGroups: ["spreadgroup.com"]
    apiVersions: ["v1"]
    resources: ["accessrequests", "accessgrants"]
    operations: ["CREATE"]
    scope: Namespaced
  clientConfig:
    service:
      namespace: default
      name: kube-request-access
    # caBundle is set by `make local-config`, DO NOT change it manually.  (this contains the base64 encoded localhost cert)
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYRENDQWtTZ0F3SUJBZ0lVVk9jTDVNbVNFSlc0Z3ZWNkR6OUY0eDR4UFhjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tqRW9NQ1lHQTFVRUF3d2ZhM1ZpWlMxeVpYRjFaWE4wTFdGalkyVnpjeTVrWldaaGRXeDBMbk4yWXpBZQpGdzB5TWpFeE1qZ3hNRFU1TURCYUZ3MHlNakV5TWpneE1EVTVNREJhTUNveEtEQW1CZ05WQkFNTUgydDFZbVV0CmNtVnhkV1Z6ZEMxaFkyTmxjM011WkdWbVlYVnNkQzV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDd0txU1N2UCtrT21SM0FteDhpaU1FTHJCRWZhclRTcW1taFJ0TEhJdXBTckMybUo3WAplRS9Xai8rRm45dHhqYUx4bkFyRUd3OXdFem0xOVo1em1GR2VyNEQxcVp5cDlLdmFXaGx4dVN0R1BwQVlJRG4wCkVnZE9LRm1PR1RQM0FFMFlMYytGeUJHMUpQem41ZnRlci9DeUlnNHhKaFhyRFJJektzcnVyMkRmT0NqdWVpMjIKMmxJTjRoU2diVHFEcTZIeS9aalB6YjI3b2lvTVVzMW9lc2xqZjQzQ1BGL1prTDdhUlFNVzl4N3hWRHdJZmZ2egoxV2hVQVhDdnhSbVBWTjNQNEtlWHVIMXBoNzVsbCs5ZGhKKzNLdjZnRXZpV1dWemNKZWdCWklhVGxMYXRuNkE4ClBicXNtUmwvdVluaSt3d2RZTnNTd2tnZHRkVms0aGpCUERpOUFnTUJBQUdqZWpCNE1EVUdBMVVkRVFRdU1DeUMKSDJ0MVltVXRjbVZ4ZFdWemRDMWhZMk5sYzNNdVpHVm1ZWFZzZEM1emRtT0NDV3h2WTJGc2FHOXpkREFMQmdOVgpIUThFQkFNQ0I0QXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3SFFZRFZSME9CQllFRk03K1VOWkVlN0JsClJzenA2YjJIRWxLM0NDZXlNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNvbUtFSVc2ZWxaQVNlY1c2TUhGS0sKLzJOTTJXK3hsSXk0N2YzT3JtL216ckpTOGpaWGtvTis5S21ramlFUkJCTGFMSkQxZURqZ3I0TmIxaWRkUzlabApCeGppQmVNcThQZElpSE1PcUpKbUx5aUxYMFFSSG0zcFY3eFkwaEhiL2xvN1dheDErVk5tbVk2YkxWWmFCcndyCllFV3hZUmtkQ3JjeFBuYXJIeUhoZkZVK0hHeXlkSm5BMVVzeFFxeGN4b0hVSmFwTFdMakRpZ2pVL0JSWWgrUW0Kd2FnOEtEbVpyN3RkaytYQi9jVzdCYlY5dXNoWVJjSXJQaVduUk1WcERzSlRUNnQvWE5GWisyeGZXWFhTYWRqcAppZG10WW5RTnFBT1I2ZEVvcmRnTjh6RjRBM0NiajJROHI4aWx0dXhHSnE3THFFN3VKazYwYnpZN0xqUkU5czE5Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"  # CA_BUNDLE
  admissionReviewVersions: ["v1"]
  sideEffects: NoneOnDryRun
  timeoutSeconds: 5
